<?php

/**
 * $ php artisan optimize (APP_ENVをlocalとしている場合は、--forceオプションを追加してください)
 * コマンドで行われるフレームワークコアソースコードの最適化に、
 * 実装したコードを含める場合に利用します。
 * 主にアプリケーションの実行速度改善などに利用されます。
 *
 * routes.phpやconfig配下の設定ファイルなどは、
 * それぞれキャッシュファイル作成コマンドを利用するため、ここに含めません。
 */
return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    | ユーザーの実装コードは以下のように追記します
    */

    'files' => [
        // Authenticate Custom Driver
        app_path('Authenticate/UserCacheProvider.php'),
        // View Composer
        app_path('Composers/UserComposer.php'),
        // DataAccess Class(Cache)
        app_path('DataAccess/Cache/Cacheable.php'),
        app_path('DataAccess/Cache/DataCache.php'),
        // DataAccess Class(EloquentORM)
        app_path('DataAccess/Eloquent/Comment.php'),
        app_path('DataAccess/Eloquent/Entry.php'),
        app_path('DataAccess/Eloquent/User.php'),
        app_path('DataAccess/Eloquent/SaveTransactionalTrait.php'),
        // Exception Handlers
        app_path('Exceptions/Handler.php'),
        // Controllers
        app_path('Http/Controllers/Controller.php'),
        app_path('Http/Controllers/EntryController.php'),
        app_path('Http/Controllers/CommentController.php'),
        app_path('Http/Controllers/ApplicationController.php'),
        app_path('Http/Controllers/Admin/EntryController.php'),
        app_path('Http/Controllers/Auth/AuthController.php'),
        // Middlewares
        app_path('Http/Middleware/Authenticate.php'),
        app_path('Http/Middleware/EncryptCookies.php'),
        app_path('Http/Middleware/ExistsEntry.php'),
        app_path('Http/Middleware/RedirectIfAuthenticated.php'),
        app_path('Http/Middleware/SelfEntry.php'),
        app_path('Http/Middleware/VerifyCsrfToken.php'),
        // FormRequest Class
        app_path('Http/Requests/CommentRequest.php'),
        app_path('Http/Requests/EntryStoreRequest.php'),
        app_path('Http/Requests/EntryUpdateRequest.php'),
        app_path('Http/Requests/LoginRequest.php'),
        app_path('Http/Requests/UserRegisterRequest.php'),
        // Validator
        app_path('Http/Validators/CustomValidator.php'),
        // ServiceProviders
        app_path('Providers/AppServiceProvider.php'),
        app_path('Providers/AuthServiceProvider.php'),
        app_path('Providers/CaptchaServiceProvider.php'),
        app_path('Providers/DriverServiceProvider.php'),
        app_path('Providers/EventServiceProvider.php'),
        // LocalServiceProviderクラスは、APP_ENVがlocalの場合にのみサービスプロバイダへ登録する処理のため、
        // 最適化には含めなくても構いませんが、Homestead環境ではAPP_KEY=localとして実行されますので、
        // 実際のデプロイには含めないのが一般的です
        app_path('Providers/LocalServiceProvider.php'),
        app_path('Providers/RouteServiceProvider.php'),
        app_path('Providers/ViewServiceProvider.php'),
        /**
         * Repositories
         */
        app_path('Repositories/CommentRepository.php'),
        app_path('Repositories/CommentRepositoryInterface.php'),
        app_path('Repositories/EntryRepository.php'),
        app_path('Repositories/EntryRepositoryInterface.php'),
        app_path('Repositories/UserRepository.php'),
        app_path('Repositories/UserRepositoryInterface.php'),
        /**
         * Services
         */
        app_path('Services/CommentService.php'),
        app_path('Services/EntryService.php'),
        app_path('Services/UserService.php'),
        /**
         * helper methods
         */
        app_path('helper.php'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    | ここは主にパッケージなどで利用します。
    */

    'providers' => [

    ],

];
